import './globals.css'
import { ReactNode, Suspense } from 'react'
import { NavBar, NavBarSkeleton } from '@/modules/NavBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type RootLayoutProps = {
  children: ReactNode
}

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props

  return (
    <html lang="en">
      <body>
        <Suspense fallback={<NavBarSkeleton />}>
          {/* @ts-expect-error Async Server Component */}
          <NavBar />
        </Suspense>
        <main className="py-4 px-2">{children}</main>
      </body>
    </html>
  )
}
