import './globals.css'
import { ReactNode, Suspense } from 'react'
import { ApolloClientProvider } from '@/libs/ApolloClientProvider'
import { NavBar, NavBarSkeleton } from '@/modules/NavBar'

export const metadata = {
  title: 'PoC Next server components with Apollo',
  description: 'Generated by create next app',
}

export type RootLayoutProps = {
  children: ReactNode
}

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props

  return (
    <html lang="en">
      <body>
        <ApolloClientProvider>
          <Suspense fallback={<NavBarSkeleton />}>
            {/* @ts-expect-error Async Server Component */}
            <NavBar />
          </Suspense>
          <main className="py-4 px-2">{children}</main>
        </ApolloClientProvider>
      </body>
    </html>
  )
}
